version: 0.2

phases:
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build
  post_build:
    commands:
      - dotnet publish
      - cd test/HelloWorld.Tests
      - dotnet test
artifacts:
  files:
    - '*'
  base-directory: 'src/HelloWorld/bin/Debug/netcoreapp1.0/publish'